name: Publish

on:
  release:
    types: [ released ]

jobs:
  npm:

    name: Publish to NPM Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn run build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
